Fruitables/Fruitables/Controllers/ProductsController.cs
using Fruitables.Models;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Fruitables.Controllers
{
    public class ProductsController : Controller
    {
        private fruitablesEntities5 db = new fruitablesEntities5();

        // عرض قائمة المنتجات
        public ActionResult Index()
        {
            var products = db.products.ToList();
            return View(products);
        }

        // عرض نموذج إضافة منتج جديد
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(product model, HttpPostedFileBase upload)
        {
            if (ModelState.IsValid)
            {
                if (upload != null && upload.ContentLength > 0)
                {
                    string path = Path.Combine(Server.MapPath("~/Images"), Path.GetFileName(upload.FileName));
                    upload.SaveAs(path);
                    model.img = "/Images/" + Path.GetFileName(upload.FileName);
                }

                db.products.Add(model);
                db.SaveChanges();

                return RedirectToAction("Home");
            }

            return View(model);
        }

        public ActionResult About()
        {
            return View();
        }
      
        public ActionResult Details(int id)
        {
            var product = db.products.Find(id);

            return View("DetailsItme");
        }

        public ActionResult DetailsItme(int id)
        {
            var product = db.products.Find(id);

            return View(product);
        }

        public ActionResult Home()
        {

            return View();

        }

        public ActionResult AddToCart()
        {

            var cart = db.CartItems.Include(x=>x.product).ToList();

            return View(cart);

        }

        // إضافة منتج إلى السلة
        [HttpPost]
        public ActionResult Add(int id)
        {
            var product = db.products.Find(id);
            if (product != null)
            {
                var cartItem = db.CartItems.SingleOrDefault(c => c.ProductId == id);
                if (cartItem != null)
                {
                    cartItem.Quantity++;
                    db.Entry(cartItem).State = EntityState.Modified;

                }
                else
                {
                    CartItem cartItem1 = new CartItem();
                    cartItem1.Quantity = 1;
                    cartItem1.registrationid =1; //لازم اغيرو بناء على اليوزر الي داخل 
                    cartItem1.ProductId = id;
                    cartItem = cartItem1;
                    db.CartItems.Add(cartItem);
                   
                }
                db.SaveChanges();
            }

            return RedirectToAction("AddToCart");
        }





        [HttpPost]
        public ActionResult RemoveFromCart(int id)
        {
            var cartItem = db.CartItems.Find(id);
            if (cartItem != null)
            {
                db.CartItems.Remove(cartItem);
                db.SaveChanges();
            }
            return RedirectToAction("Index");
        }
        //public ActionResult ViewCart()
        //{
        //    var cartItems = db.CartItems
        //        .Include(c => c.id  )  
        //        .ToList();

        //    return View(cartItems);
        //}

        // عرض سلة التسوق
        //public ActionResult showitem()
        //{
        //    var cartItems = db.CartItems.Include("Product").ToList();
        //    return View(cartItems);
        //}

    }
}

Fruitables/Fruitables/Controllers/registrationsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Fruitables.Models;

namespace Fruitables.Controllers
{
    public class registrationsController : Controller
    {
        private fruitablesEntities5 db = new fruitablesEntities5();

        // GET: registrations
        public ActionResult Index()
        {
            return View(db.registrations.ToList());
        }

        // GET: registrations/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            registration registration = db.registrations.Find(id);
            if (registration == null)
            {
                return HttpNotFound();
            }
            return View(registration);
        }

        // GET: registrations/Create
        public ActionResult registrations()
        {
            return View();
        }

        // POST: registrations/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult registrations([Bind(Include = "id,img,name,email,password,Confirm_password,status")] registration registration)
        {
            if (ModelState.IsValid)
            {
                db.registrations.Add(registration);
                db.SaveChanges();
                return RedirectToAction("Index");
            }


            return View(registration);
        }



        public ActionResult Profile(int id)
        {
            var user = db.registrations.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Profile(registration model)
        {
            if (ModelState.IsValid)
            {
                db.Entry(model).State = EntityState.Modified;
                db.SaveChanges();
                ViewBag.Message = "Profile updated successfully!";
            }
            return View(model);
        }





        //login
        public ActionResult login()
        {
            return View();
        }


    }










}

    


   

Fruitables/Fruitables/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Fruitables - Vegetable Website Template</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;600&family=Raleway:wght@600;800&display=swap" rel="stylesheet">

    <!-- Icon Font Stylesheet -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="~/lib/lightbox/css/lightbox.min.css" rel="stylesheet">
    <link href="~/lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">


    <!-- Customized Bootstrap Stylesheet -->
    <link href="~/css/bootstrap.min.css" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="~/css/style.css" rel="stylesheet">


    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <style>
        .fixed-top {
            position: sticky;
        }
    </style>

</head>
<body>

    <!-- Spinner Start -->
    <div id="spinner" class="show w-100 vh-100 bg-white position-fixed translate-middle top-50 start-50  d-flex align-items-center justify-content-center">
        <div class="spinner-grow text-primary" role="status"></div>
    </div>
    <!-- Spinner End -->
    <!-- Navbar start -->
    <div class="container-fluid fixed-top">
        <div class="container topbar bg-primary d-none d-lg-block">
            <div class="d-flex justify-content-between">
                <div class="top-info ps-2">
                    <small class="me-3"><i class="fas fa-map-marker-alt me-2 text-secondary"></i> <a href="#" class="text-white">Irbad, Jorden</a></small>
                    <small class="me-3"><i class="fas fa-envelope me-2 text-secondary"></i><a href="#" class="text-white">Fruitables@gmail.com</a></small>
                </div>

            </div>
        </div>
        <div class="container px-0">
            <nav class="navbar navbar-light bg-white navbar-expand-xl">
                <a href="index.html" class="navbar-brand"><h1 class="text-primary display-6">Fruitables</h1></a>
                <button class="navbar-toggler py-2 px-3" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
                    <span class="fa fa-bars text-primary"></span>
                </button>
                <div class="collapse navbar-collapse bg-white" id="navbarCollapse">
                    <div class="navbar-nav mx-auto">
                        <a href="@Url.Action("Home", "Products")" class="nav-item nav-link active">Home</a>
                        <a href="@Url.Action("Index", "Products")" class="nav-item nav-link">Shop</a>
                        <a href="@Url.Action("AddToCart", "Products")" class="nav-item nav-link">Cart</a>
                        <a href="@Url.Action("About", "Products")" class="nav-item nav-link">About</a>

                     


                    </div>

                    <div class="d-flex m-3 me-0">
                        <a href="@Url.Action("AddToCart", "Products")" class="position-relative me-4 my-auto"><i class="fa fa-shopping-bag fa-2x"></i></a>


                        <a href="#" class="my-auto">
                            <i class="fas fa-user fa-2x"></i>
                        </a>

                        <button class="btn-search btn border border-secondary btn-md-square rounded-circle bg-white me-4 " style="margin-left: 25px; color: #81C408;" data-bs-toggle="modal" data-bs-target="#searchModal" onclick="location.href='@Url.Action("login", "registrations")'">Login </button>


                    </div>
                </div>
            </nav>
        </div>
    </div>
    <!-- Navbar End -->



    @RenderBody()


    <!-- Footer Start -->
    <div class="container-fluid bg-dark text-white-50 footer pt-5 mt-5">
        <div class="container py-5">
            <div class="pb-4 mb-4" style="border-bottom: 1px solid rgba(226, 175, 24, 0.5) ;">
                <div class="row g-4">
                    <div class="col-lg-3">
                        <a href="#">
                            <h1 class="text-primary mb-0">Fruitables</h1>
                            <p class="text-secondary mb-0">Fresh products</p>
                        </a>
                    </div>
                    <div class="col-lg-6">
                        <div class="position-relative mx-auto">
                            <input class="form-control border-0 w-100 py-3 px-4 rounded-pill" type="number" placeholder="Your Email">
                            <button type="submit" class="btn btn-primary border-0 border-secondary py-3 px-4 position-absolute rounded-pill text-white" style="top: 0; right: 0;">Subscribe Now</button>
                        </div>
                    </div>
                    <div class="col-lg-3">
                        <div class="d-flex justify-content-end pt-3">
                            <a class="btn  btn-outline-secondary me-2 btn-md-square rounded-circle" href=""><i class="fab fa-twitter"></i></a>
                            <a class="btn btn-outline-secondary me-2 btn-md-square rounded-circle" href=""><i class="fab fa-facebook-f"></i></a>
                            <a class="btn btn-outline-secondary me-2 btn-md-square rounded-circle" href=""><i class="fab fa-youtube"></i></a>
                            <a class="btn btn-outline-secondary btn-md-square rounded-circle" href=""><i class="fab fa-linkedin-in"></i></a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row g-5">
                <div class="col-lg-3 col-md-6">
                    <div class="footer-item">
                        <h4 class="text-light mb-3">Why People Like us!</h4>
                        <p class="mb-4">typesetting, We excel at the typesetting store, our products are always fresh, including vegetables and fruits.</p>
                        <a href="" class="btn border-secondary py-2 px-4 rounded-pill text-primary">Read More</a>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <div class="d-flex flex-column text-start footer-item">
                        <h4 class="text-light mb-3">Shop Info</h4>
                        <a class="btn-link" href="">About Us</a>
                        <a class="btn-link" href="">Contact Us</a>

                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <div class="d-flex flex-column text-start footer-item">
                        <h4 class="text-light mb-3">Account</h4>
                        <a class="btn-link" href="">My Account</a>
                        <a class="btn-link" href="">Shop details</a>
                        <a class="btn-link" href="">Shopping Cart</a>

                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <div class="footer-item">
                        <h4 class="text-light mb-3">Contact</h4>
                        <p>Address: Irbad, Jorden</p>
                        <p>Email: typesetting@gmail.com</p>
                        <p>Phone: +0962 7994 8276</p>
                        <p>Payment Accepted</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Footer End -->
    <!-- Copyright Start -->
    <div class="container-fluid copyright bg-dark py-4">
        <div class="container">
            <div class="row">
                <div class="col-md-6 text-center text-md-start mb-3 mb-md-0">
                    <span class="text-light"><a href="#"><i class="fas fa-copyright text-light me-2"></i>typesetting </a>, All right reserved.</span>
                </div>

            </div>
        </div>
    </div>
    <!-- Copyright End -->
    <!-- Back to Top -->
    <a href="#" class="btn btn-primary border-3 border-primary rounded-circle back-to-top"><i class="fa fa-arrow-up"></i></a>


    <!-- JavaScript Libraries -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/easing/easing.min.js"></script>
    <script src="~/lib/waypoints/waypoints.min.js"></script>
    <script src="~/lib/lightbox/js/lightbox.min.js"></script>
    <script src="~/lib/owlcarousel/owl.carousel.min.js"></script>

    <!-- Template Javascript -->
    <script src="~/js/main.js"></script>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

</body>
</html>